# These are your funding links that will appear on your GitHub profile
github: brazilianscriptguy # Your GitHub username
paypal: luizhamilton.lhr@gmail.com # Your PayPal email
Brazilian PIX Code: 00020126590014br.gov.bcb.pix0114+55969811552650219@brazilianscriptguy520400005303986540550.005802BR5924Luiz Hamilton Roberto da6008Brasilia62090505zlxqq63046659
