name: Build and Release

on:
  workflow_dispatch:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Set up PowerShell
        uses: actions/setup-powershell@v3 # Corrected action name (v3 is recommended)
        with:
          pwsh-version: '7.3.0' # Or your preferred version

      - name: Build and package artifacts
        id: package
        run: |
          # ... (Your PowerShell packaging script remains the same)
          echo "package-path=$(Resolve-Path Package-ProSuite.zip).Path" >> $env:GITHUB_OUTPUT

      - name: Compute SHA256 hash
        id: compute_hash
        run: |
          $hash = Get-FileHash -Path ${{ steps.package.outputs.package-path }} -Algorithm SHA256 | Select-Object -ExpandProperty Hash
          echo "::set-output name=hash::$hash" # Use the recommended output syntax

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ steps.package.outputs.package-path }}
          asset_name: Package-ProSuite.zip
          asset_content_type: application/zip

      - name: Update Release Notes with SHA256 Hash
        if: ${{ steps.compute_hash.outputs.hash != '' }}
        uses: actions/github-script@v6 # Corrected action name (and use v6 or later)
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const hash = '${{ steps.compute_hash.outputs.hash }}';
            const release = context.payload.release; # Get the release object
            const releaseId = release.id;
            const currentBody = release.body || '';
            const updatedBody = `${currentBody}\n\n**SHA256 Hash of Package-ProSuite.zip:** \`${hash}\``;

            await github.rest.repos.updateRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: releaseId,
              body: updatedBody
            });
