name: CI/CD Workflow for PowerShell Module

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Update and resolve dependencies
      - name: Update and Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get upgrade -y
          sudo apt-get autoremove -y
          sudo apt-get autoclean
          sudo apt-get remove -y containerd || true
          sudo apt-get install -y containerd.io jq docker.io

      # Build the PowerShell module
      - name: Build PowerShell Module
        run: |
          pwsh -Command "Import-Module ./YourModule.psd1; Test-ModuleManifest -Path ./YourModule.psd1"

      # Run tests for the module
      - name: Run PowerShell Tests
        run: |
          pwsh -Command "Invoke-Pester -Path ./Tests -Output Detailed"

      # Package the PowerShell Module
      - name: Package PowerShell Module
        run: |
          mkdir -p ./dist
          zip -r ./dist/YourModule.zip ./YourModule.psd1 ./YourModule.psm1 ./YourModule/*.ps1

      # Publish the package to GitHub Packages
      - name: Publish to GitHub Packages
        uses: actions/upload-artifact@v3
        with:
          name: YourModule
          path: ./dist/YourModule.zip
