name: CI/CD Workflow for PowerShell Module

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Install Dependencies and PowerShell
      - name: Install Dependencies and PowerShell
        run: |
          sudo apt-get update
          sudo apt-get install -y wget apt-transport-https software-properties-common zip
          wget -q https://packages.microsoft.com/config/ubuntu/$(lsb_release -rs)/packages-microsoft-prod.deb
          sudo dpkg -i packages-microsoft-prod.deb
          sudo apt-get update
          sudo apt-get install -y powershell

      # Locate the PowerShell module file
      - name: Locate PowerShell Module
        run: |
          MODULE_FILE=$(find . -name "Windows-SysAdmin-ProSuite.psd1" | head -n 1)
          if [ -z "$MODULE_FILE" ]; then
            echo "Error: Windows-SysAdmin-ProSuite.psd1 not found in the repository!" && exit 1
          fi
          echo "Module file located at: $MODULE_FILE"
          echo "MODULE_FILE=$MODULE_FILE" >> $GITHUB_ENV

      # Build the PowerShell Module
      - name: Build PowerShell Module
        shell: pwsh
        run: |
          try {
            Import-Module "$env:MODULE_FILE" -ErrorAction Stop
            Test-ModuleManifest -Path "$env:MODULE_FILE" -ErrorAction Stop
          } catch {
            Write-Error "Failed to import or validate the module manifest: $_"
            exit 1
          }

      # Run PowerShell Tests
      - name: Run PowerShell Tests
        shell: pwsh
        run: |
          Invoke-Pester -Path ./Tests -Output Detailed

      # Package the PowerShell Module
      - name: Package PowerShell Module
        run: |
          MODULE_DIR=$(dirname "$env:MODULE_FILE")
          mkdir -p ./dist
          zip -r ./dist/Windows-SysAdmin-ProSuite.zip "$MODULE_DIR"

      # Upload the Package as an Artifact
      - name: Upload Package to GitHub
        uses: actions/upload-artifact@v3
        with:
          name: Windows-SysAdmin-ProSuite
          path: ./dist/Windows-SysAdmin-ProSuite.zip
