name: CI/CD Workflow for PowerShell Module

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Install dependencies
      - name: Update and Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get upgrade -y
          sudo apt-get install -y jq docker.io pwsh zip

      # Build the PowerShell module
      - name: Build PowerShell Module
        shell: pwsh
        run: |
          Import-Module ./YourModule.psd1
          Test-ModuleManifest -Path ./YourModule.psd1

      # Run tests for the module
      - name: Run PowerShell Tests
        shell: pwsh
        run: |
          Invoke-Pester -Path ./Tests -Output Detailed

      # Package the PowerShell Module
      - name: Package PowerShell Module
        run: |
          mkdir -p ./dist
          zip -r ./dist/YourModule.zip ./YourModule.psd1 ./YourModule.psm1 ./YourModule/*.ps1

      # Upload the package as an artifact
      - name: Upload Package to GitHub
        uses: actions/upload-artifact@v3
        with:
          name: YourModule
          path: ./dist/YourModule.zip
