name: Publish NuGet Package

on:
  workflow_dispatch:
  release:
    types: [published]

permissions:
  packages: write
  contents: read

jobs:
  publish-nuget-pkg:
    runs-on: ubuntu-latest

    container:
      image: mcr.microsoft.com/dotnet/sdk:7.0  # Use .NET SDK 7.0 official container

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Configure NuGet source
      - name: Configure NuGet Source
        run: |
          dotnet nuget add source \
            --name GitHub \
            --username ${{ github.repository_owner }} \
            --password ${{ secrets.NUGET_TOKEN }} \
            https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json

      # Step 3: Push the NuGet package
      - name: Publish NuGet Package
        run: |
          dotnet nuget push artifacts/Windows-SysAdmin-ProSuite.1.0.1.nupkg \
            --source "GitHub" \
            --api-key ${{ secrets.NUGET_TOKEN }} \
            --skip-duplicate
