name: Publish NuGet Package LOCAL

on:
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Install Mono and NuGet CLI
      - name: Install Mono and NuGet CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y mono-complete
          wget https://dist.nuget.org/win-x86-commandline/latest/nuget.exe -O nuget.exe
          chmod +x ./nuget.exe

      # Publish NuGet Package
      - name: Publish NuGet Package
        run: |
          mono ./nuget.exe push ./artifacts/*.nupkg \
            -ApiKey ${{ secrets.NUGET_AUTH_TOKEN }} \
            -Source "https://nuget.pkg.github.com/brazilianscriptguy/index.json"
