name: Publish NuGet Package

on:
  workflow_dispatch:
  release:
    types: [published]

permissions:
  packages: write
  contents: read

jobs:
  publish-nuget-package:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the Repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Delete Existing NuGet Package
      - name: Delete Existing Package (if any)
        env:
          NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}
        run: |
          PACKAGE_NAME="Windows-SysAdmin-ProSuite"
          PACKAGE_VERSION="1.0.1"
          OWNER="${{ github.repository_owner }}"
          DELETE_URL="https://nuget.pkg.github.com/${OWNER}/package/${PACKAGE_NAME}/${PACKAGE_VERSION}"

          echo "Attempting to delete existing package ${PACKAGE_NAME} version ${PACKAGE_VERSION}..."
          
          curl -X DELETE \
            -H "Authorization: Bearer $NUGET_TOKEN" \
            -H "Accept: application/vnd.github.package-deletion-preview+json" \
            $DELETE_URL || echo "No existing package found to delete."

      # Step 3: Push NuGet Package to GitHub
      - name: Push NuGet Package to GitHub
        env:
          NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}
        run: |
          dotnet nuget push artifacts/Windows-SysAdmin-ProSuite.1.0.1.nupkg \
            --source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" \
            --api-key $NUGET_TOKEN
