name: Publish NuGet Package

on:
  workflow_dispatch:
  release:
    types: [published]

permissions:
  packages: write
  contents: read

jobs:
  publish-nuget-package:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Push NuGet Packages to GitHub Packages
      - name: Push NuGet Packages
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.NUGET_AUTH_TOKEN }}
        run: |
          echo "Pushing NuGet packages to GitHub Packages..."
          for package in artifacts/*.nupkg; do
            echo "Processing package: $package"

            # Push package with --skip-duplicate
            dotnet nuget push "$package" \
              --source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" \
              --api-key $NUGET_AUTH_TOKEN --skip-duplicate || {
                echo "Skipping package due to conflict or duplicate: $package"
              }
          done
