name: Publish NuGet Package

on:
  workflow_dispatch:  # Allows manual triggering of the workflow
  push:
    tags:
      - 'v*'  # Trigger on tags starting with 'v'

permissions:
  contents: write
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up .NET
      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0'

      # Step 3: Update Package Version
      - name: Update Package Version
        run: |
          # Generate a timestamp version string in the format YYYYMMDD.HHmmSS
          timestamp=$(date +'%Y%m%d.%H%M%S')
          sed -i "s|<Version>.*</Version>|<Version>${timestamp}</Version>|" nuget.package.csproj
          echo "Generated version: ${timestamp}"

      # Step 4: Restore dependencies
      - name: Restore dependencies
        run: dotnet restore nuget.package.csproj

      # Step 5: Build the project
      - name: Build the project
        run: dotnet build nuget.package.csproj --configuration Release --no-restore

      # Step 6: Pack the NuGet package
      - name: Pack the NuGet package
        run: dotnet pack nuget.package.csproj --configuration Release --no-build --output ./artifacts

      # Step 7: Publish to GitHub Packages
      - name: Publish to GitHub Packages
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          dotnet nuget push ./artifacts/Scripts-PowerShell.*.nupkg --api-key $NUGET_AUTH_TOKEN --source "github" --skip-duplicate
