name: Publish NuGet Package

on:
  workflow_dispatch:
  release:
    types: [published]

permissions:
  packages: write
  contents: read

jobs:
  publish-nuget-package:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the Repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Fetch and Delete Existing NuGet Package Versions
      - name: Delete Existing NuGet Package Versions
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PACKAGE_NAME="Windows-SysAdmin-ProSuite"
          OWNER="${{ github.repository_owner }}"
          echo "Fetching old package versions for ${PACKAGE_NAME}..."

          API="https://api.github.com/orgs/${OWNER}/packages/nuget/${PACKAGE_NAME}/versions"

          # Fetch all package versions
          response=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" -H "Accept: application/vnd.github.v3+json" $API)

          # Validate the response
          if ! echo "$response" | jq empty 2>/dev/null; then
            echo "Error: Invalid response from GitHub API:"
            echo "$response"
            exit 1
          fi

          # Extract package version IDs
          echo "$response" | jq -r '.[].id' > package_ids.txt

          # Check if any package IDs exist
          if [ ! -s package_ids.txt ]; then
            echo "No existing package versions found for ${PACKAGE_NAME}."
            exit 0
          fi

          # Delete all fetched package versions
          while IFS= read -r package_id; do
            echo "Deleting version ID: $package_id"
            DELETE_URL="https://api.github.com/orgs/${OWNER}/packages/nuget/${PACKAGE_NAME}/versions/$package_id"
            curl -X DELETE -H "Authorization: Bearer $GITHUB_TOKEN" -H "Accept: application/vnd.github.v3+json" $DELETE_URL || echo "Failed to delete version ID: $package_id"
          done < package_ids.txt

          echo "Old versions of ${PACKAGE_NAME} have been cleaned."

      # Step 3: Build the NuGet Package
      - name: Build NuGet Package
        run: |
          mkdir -p artifacts
          # Ensure the .nupkg file exists in artifacts directory
          echo "Ensure the artifacts/Windows-SysAdmin-ProSuite.1.0.1.nupkg exists manually here if pre-built."

      # Step 4: Push the NuGet Package to GitHub Packages
      - name: Push NuGet Package to GitHub
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          dotnet nuget push artifacts/Windows-SysAdmin-ProSuite.1.0.1.nupkg \
            --source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" \
            --api-key $GITHUB_TOKEN --skip-duplicate
