name: Publish NuGet Package

on:
  workflow_dispatch:
  release:
    types: [published]

permissions:
  packages: write
  contents: read

jobs:
  publish-nuget-package:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Verify Package Exists
      - name: Verify NuGet Package
        run: |
          if [ ! -f "artifacts/Windows-SysAdmin-ProSuite.1.0.2.nupkg" ]; then
            echo "Error: NuGet package file not found in artifacts directory."
            exit 1
          fi

      # Step 3: Push NuGet Package to GitHub
      - name: Push NuGet Package to GitHub
        env:
          NUGET_AUTH_TOKEN: ${{ vars.NUGET_AUTH_TOKEN }}
        run: |
          echo "Pushing new NuGet package to GitHub Packages..."
          dotnet nuget push artifacts/*.nupkg \
            --source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" \
            --api-key $NUGET_AUTH_TOKEN --skip-duplicate
