name: Publish NuGet Package

on:
  workflow_dispatch:
  release:
    types: [published]

permissions:
  packages: write
  contents: read

jobs:
  publish-nuget-package:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Verify Package Exists
      - name: Verify NuGet Packages
        run: |
          if [ ! -d "artifacts" ]; then
            echo "Error: Artifacts directory does not exist."
            exit 1
          fi
          if [ -z "$(ls -A artifacts/*.nupkg 2>/dev/null)" ]; then
            echo "Error: No NuGet packages found in artifacts directory."
            exit 1
          fi
          echo "NuGet packages found in artifacts directory."

      # Step 3: Push NuGet Packages to GitHub Packages
      - name: Push NuGet Packages
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.NUGET_AUTH_TOKEN }}
        run: |
          echo "Pushing NuGet packages to GitHub Packages..."
          for package in artifacts/*.nupkg; do
            echo "Pushing package: $package"

            # Attempt to push the package and skip duplicates
            dotnet nuget push "$package" \
              --source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" \
              --api-key $NUGET_AUTH_TOKEN --skip-duplicate || {
                echo "Skipping package due to version conflict or duplicate: $package"
              }
          done
