# Step 2: Fix Dependencies and Install .NET SDK
- name: Fix Dependencies and Install .NET
  run: |
    echo "Adding required Microsoft repository for Ubuntu 22.04..."
    wget https://packages.microsoft.com/config/ubuntu/22.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
    sudo dpkg -i packages-microsoft-prod.deb
    rm packages-microsoft-prod.deb

    echo "Updating package lists..."
    sudo apt-get update || {
      echo "Error updating package lists. Retrying..."
      sudo apt-get clean
      sudo apt-get update
    }

    echo "Installing .NET SDK..."
    sudo apt-get install -y dotnet-sdk-7.0 || {
      echo "Retrying with conflict resolution..."
      sudo apt-get -o Dpkg::Options::="--force-overwrite" install -y dotnet-sdk-7.0 || {
        echo "Force installing .NET dependencies..."
        sudo apt-get install -f -y
      }
    }
