name: Publish NuGet Package

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      # Step 2: Install Mono (Required for nuget.exe on Linux)
      - name: Install Mono
        run: |
          sudo apt-get update
          sudo apt-get install -y mono-complete

      # Step 3: Install NuGet CLI
      - name: Install NuGet CLI
        run: |
          wget https://dist.nuget.org/win-x86-commandline/latest/nuget.exe -O nuget.exe
          chmod +x ./nuget.exe

      # Step 4: Generate Dynamic Version
      - name: Generate Dynamic Version
        id: generate_version
        run: |
          major=1
          minor=0
          build=$(date +'%y%m%d')
          revision=$(date +'%H%M%S')
          version="$major.$minor.$build.$revision"
          echo "version=$version" >> $GITHUB_ENV

      # Step 5: Verify Nuspec File Exists
      - name: Verify Nuspec File
        run: |
          if [ ! -f "NuGet/nuget.package.nuspec" ]; then
            echo "Error: NuGet/nuget.package.nuspec does not exist in the repository."
            exit 1
          fi
          echo "NuGet/nuget.package.nuspec found."

      # Step 6: List NuGet Directory for Debugging (Optional)
      - name: List NuGet Directory
        run: |
          echo "Listing contents of NuGet directory:"
          ls -la NuGet/

      # Step 7: Update Version in Nuspec
      - name: Update Version in Nuspec
        run: |
          sed -i "s|<version>.*</version>|<version>${{ env.version }}</version>|g" NuGet/nuget.package.nuspec

      # Step 8: Generate Placeholder .dll (if missing)
      - name: Generate Placeholder .dll (if missing)
        run: |
          mkdir -p NuGetPackageContent/lib/net7.0
          if [ ! -f "NuGetPackageContent/lib/net7.0/PlaceholderDll.dll" ]; then
              echo "Generating placeholder .dll..."
              mkdir -p PlaceholderDll
              cd PlaceholderDll
              dotnet new classlib -n PlaceholderDll
              sed -i 's/<PropertyGroup>/<PropertyGroup><Version>1.0.0<\/Version>/' PlaceholderDll/PlaceholderDll.csproj
              dotnet build PlaceholderDll/PlaceholderDll.csproj -o ../NuGetPackageContent/lib/net7.0
              cd ..
              echo "Placeholder .dll generated at NuGetPackageContent/lib/net7.0/PlaceholderDll.dll"
          else
              echo "Placeholder .dll already exists."
          fi

      # Step 9: Prepare Files for NuGet Package
      - name: Prepare Files for NuGet Package
        run: |
          mkdir -p NuGetPackageContent
          cp -r BlueTeam-Tools NuGetPackageContent/ || true
          cp -r Core-ScriptLibrary NuGetPackageContent/ || true
          cp -r ITSM-Templates-SVR NuGetPackageContent/ || true
          cp -r ITSM-Templates-WKS NuGetPackageContent/ || true
          cp -r SysAdmin-Tools NuGetPackageContent/ || true
          cp LICENSE NuGetPackageContent/ || true
          cp README.md NuGetPackageContent/ || true

      # Step 10: Pack NuGet Package Using nuget.exe
      - name: Pack NuGet Package
        run: |
          mkdir -p ./artifacts
          mono ./nuget.exe pack NuGet/nuget.package.nuspec -OutputDirectory ./artifacts
          ls ./artifacts

      # Step 11: Inspect NuGet Package (Optional)
      - name: Inspect NuGet Package
        run: |
          echo "Inspecting the contents of the package..."
          unzip -l ./artifacts/Windows-SysAdmin-ProSuite*.nupkg || true

      # Step 12: Fetch Existing NuGet Packages from GitHub Packages
      - name: Fetch Existing NuGet Packages
        id: fetch-packages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Fetching existing NuGet packages from GitHub Packages..."
          
          # Fetch package names and store in existing_packages.txt
          curl -s -H "Authorization: Bearer $GITHUB_TOKEN" \
               -H "Accept: application/vnd.github+json" \
               "https://api.github.com/users/${{ github.repository_owner }}/packages?package_type=nuget&per_page=100" | \
               jq -r '.[].name' > existing_packages.txt
          
          echo "Existing Packages:"
          cat existing_packages.txt

      # Step 13: Publish New NuGet Package Using nuget.exe
      - name: Publish NuGet Package
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          artifact_dir="artifacts"
          
          for package_path in "$artifact_dir"/*.nupkg; do
            [ -e "$package_path" ] || continue  # Skip if no .nupkg files

            package_name=$(basename "$package_path")
            echo "Processing package: $package_name"

            if grep -Fxq "$package_name" existing_packages.txt; then
              echo "Package '$package_name' already exists. Skipping..."
              continue
            fi

            echo "Pushing '$package_name' to GitHub Packages..."
            mono ./nuget.exe push "$package_path" \
              -ApiKey "$GITHUB_TOKEN" \
              -Source "https://nuget.pkg.github.com/brazilianscriptguy/index.json" \
              --skip-duplicate || {
                echo "Error: Failed to push '$package_name'."
                exit 1
              }
          done
