name: Publish NuGet Package

on:
  workflow_dispatch:
  release:
    types: [published]

permissions:
  packages: write
  contents: read

jobs:
  publish-nuget-package:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Verify Package Exists
      - name: Verify NuGet Package
        run: |
          if [ ! -f "artifacts/Windows-SysAdmin-ProSuite.1.0.1.nupkg" ]; then
            echo "Error: NuGet package file not found in artifacts directory."
            exit 1
          fi

      # Step 3: Clean Up Old Versions (Optional)
      - name: Clean Up Old Package Versions
        env:
          PACKAGE_NAME: "Windows-SysAdmin-ProSuite"
          OWNER: ${{ github.repository_owner }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -e
          echo "Fetching old package versions for ${PACKAGE_NAME}..."

          # Determine API endpoint
          API_URL="https://api.github.com/orgs/${OWNER}/packages/nuget/${PACKAGE_NAME}/versions"

          # Fetch package versions using the API
          response=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" -H "Accept: application/vnd.github+json" "$API_URL")

          # Debug: Print the response for verification
          echo "Response from API:"
          echo "$response"

          # Check if the response is valid JSON
          if ! echo "$response" | jq empty 2>/dev/null; then
            echo "Error: Invalid JSON response from the API."
            exit 1
          fi

          # Validate the response contains an array of objects with `id`
          if ! echo "$response" | jq -e '.[0].id' 2>/dev/null; then
            echo "No existing package versions found or unexpected API response format."
            exit 0
          fi

          # Extract package version IDs
          echo "$response" | jq -r '.[].id' > package_ids.txt

          # Check if any package IDs exist
          if [ ! -s package_ids.txt ]; then
            echo "No existing package versions found for ${PACKAGE_NAME}."
            exit 0
          fi

          # Delete all fetched package versions
          while IFS= read -r package_id; do
            echo "Deleting version ID: $package_id"
            DELETE_URL="https://api.github.com/orgs/${OWNER}/packages/nuget/${PACKAGE_NAME}/versions/$package_id"
            curl -X DELETE -H "Authorization: Bearer $GITHUB_TOKEN" -H "Accept: application/vnd.github+json" "$DELETE_URL" || echo "Failed to delete version ID: $package_id"
          done < package_ids.txt

          echo "Old versions of ${PACKAGE_NAME} have been cleaned."

      # Step 4: Push New NuGet Package
      - name: Push NuGet Package to GitHub
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Pushing new NuGet package to GitHub Packages..."
          dotnet nuget push artifacts/Windows-SysAdmin-ProSuite.1.0.1.nupkg \
            --source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" \
            --api-key $GITHUB_TOKEN --skip-duplicate

      # Step 5: Debug Authentication Issues (Optional)
      - name: Debug Authentication Issues
        if: failure()
        run: |
          echo "Checking API response for authentication issues..."
          curl -v -X GET \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            "https://api.github.com/user/packages"
