name: Publish NuGet Package

on:
  workflow_dispatch:
  release:
    types: [published]

permissions:
  packages: write
  contents: read

jobs:
  publish-nuget-package:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Verify Package Exists
      - name: Verify NuGet Package
        run: |
          if [ ! -f "artifacts/Windows-SysAdmin-ProSuite.1.0.1.nupkg" ]; then
            echo "Error: NuGet package file not found in artifacts directory."
            exit 1
          fi

      # Step 3: Authenticate and Test API Access
      - name: Verify GitHub Packages Authentication
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Testing GitHub Packages API authentication..."
          curl -X GET -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/user/packages || exit 1

      # Step 4: Clean Up Old Versions (Optional)
      - name: Clean Up Old Package Versions
        env:
          PACKAGE_NAME: "Windows-SysAdmin-ProSuite"
          OWNER: ${{ github.repository_owner }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -e
          echo "Fetching old package versions for ${PACKAGE_NAME}..."

          API_URL="https://api.github.com/orgs/${OWNER}/packages/nuget/${PACKAGE_NAME}/versions"

          response=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" -H "Accept: application/vnd.github+json" "$API_URL")

          echo "Response from API:"
          echo "$response"

          if ! echo "$response" | jq empty 2>/dev/null; then
            echo "Error: Invalid JSON response from the API."
            exit 1
          fi

          if ! echo "$response" | jq -e '.[0].id' 2>/dev/null; then
            echo "No existing package versions found or unexpected API response format."
            exit 0
          fi

          echo "$response" | jq -r '.[].id' > package_ids.txt

          if [ ! -s package_ids.txt ]; then
            echo "No existing package versions found for ${PACKAGE_NAME}."
            exit 0
          fi

          while IFS= read -r package_id; do
            echo "Deleting version ID: $package_id"
            DELETE_URL="https://api.github.com/orgs/${OWNER}/packages/nuget/${PACKAGE_NAME}/versions/$package_id"
            curl -X DELETE -H "Authorization: Bearer $GITHUB_TOKEN" -H "Accept: application/vnd.github+json" "$DELETE_URL" || echo "Failed to delete version ID: $package_id"
          done < package_ids.txt

          echo "Old versions of ${PACKAGE_NAME} have been cleaned."

      # Step 5: Push New NuGet Package
      - name: Push NuGet Package to GitHub
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Pushing new NuGet package to GitHub Packages..."
          dotnet nuget push artifacts/Windows-SysAdmin-ProSuite.1.0.1.nupkg \
            --source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" \
            --api-key $GITHUB_TOKEN --skip-duplicate
