# .github/workflows/publish-nuget-package.yml
name: Publish NuGet Package

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up .NET
      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0'

      # Step 3: Update Package Version
      - name: Update Package Version
        run: |
          version="1.0.$(date +'%Y%m%d%H%M%S')"
          sed -i "s|<Version>.*</Version>|<Version>${version}</Version>|" nuget.package.csproj

      # Step 4: Restore dependencies
      - name: Restore dependencies
        run: dotnet restore

      # Step 5: Build the project
      - name: Build the project
        run: dotnet build --configuration Release --no-restore

      # Step 6: Pack the NuGet package
      - name: Pack the NuGet package
        run: dotnet pack --configuration Release --no-build --output ./artifacts

      # Step 7: Publish to GitHub Packages
      - name: Publish to GitHub Packages
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          dotnet nuget push ./artifacts/*.nupkg --api-key $NUGET_AUTH_TOKEN --source "github" --skip-duplicate
