# .github/workflows/releases-sysadmin-ITSMs-Templates-GPOs-Templates.yml
name: Build and Release

on:
  workflow_dispatch:
  release:
    types: [published]
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: write

jobs:
  cleanup-old-releases:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Delete older releases
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh auth setup-git
          gh release list --json tagName,createdAt | jq -r '. | sort_by(.createdAt) | .[0:-1] | .[].tagName' | while read tag; do
            echo "Deleting old release: $tag"
            gh release delete "$tag" -y || echo "Failed to delete release: $tag"
            git push --delete origin "$tag" || echo "Failed to delete tag: $tag"
          done

  build-and-release-SysAdminToolSet:
    needs: cleanup-old-releases
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y zip jq gh

      - name: Generate Tag and Release Names for SysAdminToolSet
        id: generate_scripts_names
        run: |
          echo "tag_name=SysAdminToolSet" >> $GITHUB_ENV
          echo "release_name=SysAdminToolSet.zip" >> $GITHUB_ENV

      - name: Create New Release for SysAdminToolSet
        if: github.event_name != 'release'
        id: create_scripts_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.tag_name }}
          release_name: ${{ env.release_name }}
          body: "Latest automated specialized release for SysAdminToolSet."
          draft: false
          prerelease: false

      - name: Build and package SysAdminToolSet
        id: package_scripts
        run: |
          mkdir -p SysAdminToolSet
          cp LICENSE SysAdminToolSet/ || true
          cp README.md SysAdminToolSet/ || true

          # Copy only Launch-Script-AutomaticMenu.ps1 to SysAdminToolSet root
          cp Core-ScriptLibrary/Launch-Script-AutomaticMenu.ps1 SysAdminToolSet/ || true

          # Copy all directories except excluded ones
          for dir in */ ; do
              dir=${dir%/}
              if [[ "$dir" != "SysAdminToolSet" && "$dir" != ".git" && "$dir" != ".github" && "$dir" != "ITSM-Templates-WKS" && "$dir" != "ITSM-Templates-SVR" && "$dir" != "Core-ScriptLibrary" && "$dir" != "SysAdmin-Tools/GroupPolicyObjects-Templates" ]]; then
                  mkdir -p SysAdminToolSet/"$dir"
                  cp -r "$dir"/* SysAdminToolSet/"$dir"/ || true
              fi
          done

          zip -r SysAdminToolSet.zip SysAdminToolSet
          echo "package_path=$(pwd)/SysAdminToolSet.zip" >> $GITHUB_ENV

      - name: Upload SysAdminToolSet Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_scripts_release.outputs.upload_url }}
          asset_path: ${{ env.package_path }}
          asset_name: SysAdminToolSet.zip
          asset_content_type: application/zip

  build-and-release-itsm-templates-wks:
    needs: cleanup-old-releases
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y zip jq

      - name: Handle Existing ITSM-Templates-WKS Tag
        id: handle_itsm_wks_tag
        run: |
          if gh release view ITSM-Templates-WKS > /dev/null 2>&1; then
            echo "Tag ITSM-Templates-WKS exists. Deleting it."
            gh release delete ITSM-Templates-WKS -y || echo "Failed to delete release."
            git push --delete origin ITSM-Templates-WKS || echo "Failed to delete tag."
          fi

      - name: Create New Release for ITSM-Templates-WKS
        id: create_itsm_wks_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ITSM-Templates-WKS
          release_name: ITSM-Templates-WKS.zip
          body: "Latest automated specialized release for ITSM-Templates-WKS."
          draft: false
          prerelease: false

      - name: Build and package ITSM-Templates-WKS
        id: package_itsm_wks
        run: |
          zip -r ITSM-Templates-WKS.zip ITSM-Templates-WKS
          echo "package_path=$(pwd)/ITSM-Templates-WKS.zip" >> $GITHUB_ENV

      - name: Upload ITSM-Templates-WKS Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_itsm_wks_release.outputs.upload_url }}
          asset_path: ${{ env.package_path }}
          asset_name: ITSM-Templates-WKS.zip
          asset_content_type: application/zip

  build-and-release-itsm-templates-svr:
    needs: cleanup-old-releases
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y zip jq gh

      - name: Handle Existing ITSM-Templates-SVR Tag
        id: handle_itsm_svr_tag
        run: |
          if gh release view ITSM-Templates-SVR > /dev/null 2>&1; then
            echo "Tag ITSM-Templates-SVR exists. Deleting it."
            gh release delete ITSM-Templates-SVR -y || echo "Failed to delete release."
            git push --delete origin ITSM-Templates-SVR || echo "Failed to delete tag."
          fi

      - name: Create New Release for ITSM-Templates-SVR
        id: create_itsm_svr_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ITSM-Templates-SVR
          release_name: ITSM-Templates-SVR.zip
          body: "Latest automated specialized release for ITSM-Templates-SVR."
          draft: false
          prerelease: false

      - name: Build and package ITSM-Templates-SVR
        id: package_itsm_svr
        run: |
          zip -r ITSM-Templates-SVR.zip ITSM-Templates-SVR
          echo "package_path=$(pwd)/ITSM-Templates-SVR.zip" >> $GITHUB_ENV

      - name: Upload ITSM-Templates-SVR Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_itsm_svr_release.outputs.upload_url }}
          asset_path: ${{ env.package_path }}
          asset_name: ITSM-Templates-SVR.zip
          asset_content_type: application/zip

  build-and-release-GPOs-Templates:
    needs: cleanup-old-releases
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y zip jq

      - name: Handle Existing GPOs-Templates Tag
        run: |
          if gh release view GPOs-Templates > /dev/null 2>&1; then
            echo "Tag GPOs-Templates exists. Deleting it."
            gh release delete GPOs-Templates -y || echo "Failed to delete release."
            git push --delete origin GPOs-Templates || echo "Failed to delete tag."
          fi

      - name: Create New Release for GPOs-Templates
        id: create_gpos_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: GPOs-Templates
          release_name: GPOs-Templates.zip
          body: "Latest automated specialized release for GPOs-Templates."
          draft: false
          prerelease: false

      - name: Build and package GPOs-Templates
        id: package_gpos
        run: |
          mkdir -p GPOs-Templates
          cp -r SysAdmin-Tools/GroupPolicyObjects-Templates/* GPOs-Templates/ || true
          cp SysAdmin-Tools/ActiveDirectory-Management/Export-n-Import-GPOsTool.ps1 GPOs-Templates/ || true
          zip -r GPOs-Templates.zip GPOs-Templates
          echo "package_path=$(pwd)/GPOs-Templates.zip" >> $GITHUB_ENV

      - name: Upload GPOs-Templates Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_gpos_release.outputs.upload_url }}
          asset_path: ${{ env.package_path }}
          asset_name: GPOs-Templates.zip
          asset_content_type: application/zip
