# .github/workflows/SLSA-ProSuite-Publish.yml

name: SLSA-ProSuite-Publish

on:
  workflow_dispatch:
  release:
    types: [created]

permissions:
  contents: write
  id-token: write  # Ensure the workflow has write access to ID tokens

jobs:
  build:
    runs-on: windows-latest
    outputs:
      digests: ${{ steps.hash.outputs.digests }}

    steps:
      # Step 1: Check out the repository
      - uses: actions/checkout@v4

      # Step 2: Build and package artifacts
      - name: Build and package artifacts
        run: |
          mkdir build
          # Copy PowerShell scripts
          copy *.ps1 build || exit 0
          # Copy VBScript files
          copy *.vbs build || exit 0
          # Copy documentation files
          copy README.md build || exit 0
          copy LICENSE build || exit 0

          # Create a ZIP file for release
          powershell Compress-Archive -Path build\* -DestinationPath Package-ProSuite.zip

      # Step 3: Generate provenance hashes
      - name: Generate provenance subjects
        id: hash
        run: |
          $files = Get-ChildItem -Path build\*
          $hashes = @()
          foreach ($file in $files) {
              $hash = (Get-FileHash $file.FullName -Algorithm SHA256).Hash
              $hashes += "$($file.FullName): $hash"
          }
          $digestOutput = [System.Convert]::ToBase64String([System.Text.Encoding]::UTF8.GetBytes($hashes -join "`n"))
          echo "digests=$digestOutput" >> $env:GITHUB_OUTPUT

      # Step 4: Upload artifact for provenance (optional but recommended)
      - name: Upload artifact for provenance
        uses: actions/upload-artifact@v3
        with:
          name: Package-ProSuite
          path: Package-ProSuite.zip

      # Optional: Debug logs
      - name: Debug artifacts
        run: |
          dir build
          dir Package-ProSuite.zip

  provenance:
    needs: build
    runs-on: ubuntu-latest  # SLSA generator is optimized for Linux environments
    permissions:
      actions: read
      id-token: write
      contents: write
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@v1.4.0
    with:
      base64-subjects: "${{ needs.build.outputs.digests }}"
