name: SLSA-ProSuite-Publish

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      digests: ${{ steps.hash.outputs.digests }}

    steps:
      # 1) Check out the repository
      - uses: actions/checkout@v4

      # 2) Build and package artifacts
      - name: Build and package artifacts
        run: |
          mkdir -p build
          # Copy scripts
          cp *.ps1 build/ || true
          cp *.vbs build/ || true
          # Copy doc files
          cp README.md build/ || true
          cp LICENSE build/ || true

          # Create tarball for release
          tar -czf Package-ProSuite.tar.gz -C build .

      # 3) Generate provenance hashes
      - name: Generate provenance subjects
        id: hash
        run: |
          files=$(ls build/*)
          echo "digests=$(sha256sum $files | base64 -w0)" >> "${GITHUB_OUTPUT}"

      # Optional: Debug logs
      - name: Debug artifacts
        run: |
          ls -lh build/
          ls -lh Package-ProSuite.tar.gz

  provenance:
    needs: [build]
    permissions:
      actions: read
      id-token: write
      contents: write
    steps:
      # 1) Ensure Rekor public keys and TUF metadata are up to date
      - name: Update Rekor public keys
        run: |
          sudo apt-get update
          sudo apt-get install -y sigstore-cli
          sigstore-init --refresh-tuf-metadata

      # 2) Run SLSA generator
      - name: Generate SLSA provenance
        uses: slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@v1.4.0
        with:
          base64-subjects: "${{ needs.build.outputs.digests }}"

      # Optional: Debug provenance generation
      - name: Debug provenance output
        run: ls -lh ./provenance/
