# SLSA-ProSuite-Publish.yml
# This workflow generates SLSA Level 3 provenance for the Windows-SysAdmin-ProSuite repository.
# It automates artifact creation, hashing, and triggers the slsa-framework generator to produce a provenance statement.

name: SLSA-ProSuite-Publish

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      digests: ${{ steps.hash.outputs.digests }}

    steps:
      # 1) Check out repository
      - uses: actions/checkout@v4

      # 2) Build/package artifacts
      - name: Build and package artifacts
        run: |
          mkdir -p build
          # Copy PowerShell scripts (optional)
          cp *.ps1 build/ 2>/dev/null || true
          # Copy VBScript files (optional)
          cp *.vbs build/ 2>/dev/null || true
          # Copy doc files
          cp README.md build/ 2>/dev/null || true
          cp LICENSE build/ 2>/dev/null || true

          # Create a tarball for release
          tar -czf Package-ProSuite.tar.gz -C build .

      # 3) Generate provenance subject hashes (base64-encoded)
      - name: Generate provenance subjects
        id: hash
        run: |
          # Hash each file in ./build, then base64-encode
          files=$(ls build/*)
          echo "digests=$(sha256sum $files | base64 -w0)" >> "${GITHUB_OUTPUT}"

      # Optional: debug logs
      - name: Debug artifacts
        run: |
          ls -lh build/
          ls -lh Package-ProSuite.tar.gz

  provenance:
    needs: [build]
    permissions:
      actions: read
      id-token: write
      contents: write
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@v1.4.0
    with:
      # Provide the base64-encoded subject hashes to the generator
      base64-subjects: "${{ needs.build.outputs.digests }}"
