#<#
#.SYNOPSIS
#    GitHub Actions Workflow: Windows-based CI with RSAT + Pester

#.DESCRIPTION
#    Checks out code in ./repo, locates Manifest-ProSuite.psd1,
#    validates the manifest, runs Pester tests, packages an artifact.

#.AUTHOR
#    Luiz Hamilton Silva - @brazilianscriptguy

#.VERSION
#    Last Updated: December 29, 2024
#>

name: CI/CD Workflow for Windows-SysAdmin-ProSuite

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
      - name: Enable long paths
        shell: powershell
        run: git config --system core.longpaths true

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          path: repo

      - name: Install RSAT (Active Directory)
        shell: powershell
        run: |
          Write-Host "Installing RSAT for Active Directory..."
          $feat = Get-WindowsFeature RSAT-AD-PowerShell -ErrorAction SilentlyContinue
          if ($feat -and $feat.Name -eq 'RSAT-AD-PowerShell') {
              if (-not $feat.Installed) {
                  Install-WindowsFeature RSAT-AD-PowerShell
              }
          }
          else {
              Add-WindowsCapability -Online -Name "Rsat.ActiveDirectory.DS-LDS.Tools~~~~0.0.1.0"
          }
          Write-Host "RSAT ActiveDirectory tools installed."

      - name: Locate Manifest-ProSuite
        id: locate-module
        shell: powershell
        run: |
          $moduleFile = Get-ChildItem -Path './repo' -Filter "Manifest-ProSuite.psd1" -Recurse | Select-Object -First 1
          if (-not $moduleFile) {
            Write-Error "Error: Manifest-ProSuite.psd1 not found in ./repo!"
            exit 1
          }
          Write-Host "Module file: $($moduleFile.FullName)"
          echo "MODULE_FILE=$($moduleFile.FullName)" >> $Env:GITHUB_ENV

      - name: Validate Manifest
        shell: powershell
        run: |
          try {
            $modulePath = $Env:MODULE_FILE
            Write-Host "Validating manifest at: $modulePath"
            Test-ModuleManifest -Path $modulePath -ErrorAction Stop
            Write-Host "Module manifest validation successful."
          }
          catch {
            Write-Error "Failed to validate the manifest: $_"
            exit 1
          }

      - name: Run Pester Tests
        shell: powershell
        run: |
          try {
            Write-Host "Ensuring AD is loaded..."
            if (-not (Get-Module ActiveDirectory)) {
              Import-Module ActiveDirectory -ErrorAction SilentlyContinue
            }

            Write-Host "Importing module before tests..."
            Import-Module $Env:MODULE_FILE -ErrorAction Stop

            Write-Host "Running Pester tests..."
            Invoke-Pester -Path ./repo/Tests -Output Detailed

            Write-Host "Pester tests completed successfully."
          }
          catch {
            Write-Error "Pester tests failed: $_"
            exit 1
          }

      - name: Package the Module
        shell: powershell
        run: |
          $moduleDir = Split-Path $Env:MODULE_FILE
          if (-not (Test-Path './dist')) {
            New-Item -Path './dist' -ItemType Directory | Out-Null
          }
          $zipPath = Join-Path -Path './dist' -ChildPath 'Windows-SysAdmin-ProSuite.zip'
          Compress-Archive -Path "$moduleDir/*" -DestinationPath $zipPath -Force
          Write-Host "Packaging complete. Archive saved at $zipPath."

      - name: Upload Module Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Windows-SysAdmin-ProSuite
          path: ./dist/Windows-SysAdmin-ProSuite.zip

# End of script
